# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               codegov
tagline:             '一心做一把剑'
description:         '带你走进代码世界，那里充满思想、充满设计和充满惊奇。联系我 <a href="http://weibo.com/u/2422306623?source=blog&is_all=1" target="_blank">@火_爆_了</a>.'
url:                 https://yq.aliyun.com/u/codegov
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              火爆了
  url:               http://weibo.com/u/2422306623?source=blog&is_all=1
  email:             codegov@qq.com

# Custom vars
version:             1.0.0
